### ISSUE TITLE
Required header has been removed

### ISSUE THREAD

**Issue by mtdew365** [syzygy1/tb#15]
/usr/include/bits/sigset.h has been removed upstream in the glibc-headers package.

Ubuntu...
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1720339

Fedora 27....
I don't see it in the latest version.

Error...

make[1]: *** No rule to make target '/usr/include/bits/sigset.h', needed by 'threads.o'.  Stop.

**Comment by syzygy1** [comment]
Delete the .depsr directory and try again.
