### ISSUE TITLE
skrinking the syzygytb

### ISSUE THREAD

**Issue by MehdiMhalla** [syzygy1/tb#2]
is it possible to make an adapted tb shrinking for an engine : 
considerer three parameter : 
depth DEFAULT 20, 
min threshold DEFAULT 10 centipawn ,
 max threshold DEFAULT 100 centipawn,
take the tb and  keep only the positions that  a 1 thread analysis at fixed depth 20 evaluate less than max threshold and that are winning and the posistions evaluated less than minthreshold and that are DRAW. It should shrink the TB really needed for syzygysf by huge factor if it is possible and still contain all the information an engine might need.
Mehdi

**Comment by oscardssmith** [comment]
I think it might be worth reconsidering this given some experiments I've done with neural nets of the lc0 variety for endgame compression. I've found that a single 6 block, 48 filter net is able to correctly predict WDL information for about 98.5% of 6 man positions. For reference, such a net is about 1mb and on a high-end consumer graphics card can be evaluated roughly 1 billion times per second. With these numbers, generating full set of 6 man tables would take roughly 40 days. 7 man would be 11 years with this setup, but this could be done in a distributed manner, and if we used some of the Lc0 community for help, it could also be done in several months. It is worth noting that DTZ tables could likely be compressed using a very similar method, and that higher accuracy could likely be achieved than those I got with more time and effort.
