### ISSUE TITLE
PicoChess Error 6 Man Syzygy, 32 Bit  

### ISSUE THREAD

**Issue by MichaelB7** [syzygy1/tb#27]
On a Raspberry Pi  (CPU  armv7 , 32 bit OS Linux) , with 6 man syzygy tablebases, and 1GB ram, position fen 2bk4/Pp1pr3/3K3N/2P5/2P5/8/8/8 w - -, we get this error on the 9th ply 
(code modified for the following output)
set syzygypath /opt/picochess/tablebases/syzygy
info string Found 510 tablebases
Confirmation: syzygypath set to /opt/picochess/tablebases/syzygy
position fen  2bk4/Pp1pr3/3K3N/2P5/2P5/8/8/8 w - -

go depth 9
info depth 1 seldepth 3 multipv 1 score cp 190 nodes 47 nps 9400 tbhits 0 time 5 pv a7a8q
info depth 2 seldepth 4 multipv 1 score cp 190 nodes 73 nps 14600 tbhits 0 time 5 pv a7a8q e7e6 d6d5 e6h6
info depth 3 seldepth 5 multipv 1 score cp 190 nodes 93 nps 18600 tbhits 0 time 5 pv a7a8q e7e6 d6d5 e6h6 a8b8
info depth 4 seldepth 6 multipv 1 score cp 190 nodes 129 nps 21500 tbhits 0 time 6 pv a7a8q e7e6 d6d5 e6h6 a8b8 h6e6
info depth 5 seldepth 7 multipv 1 score cp 190 nodes 178 nps 29666 tbhits 0 time 6 pv a7a8q e7e6 d6d5 e6h6 a8b8 h6e6 d5d4
info depth 6 seldepth 8 multipv 1 score cp 190 nodes 244 nps 40666 tbhits 0 time 6 pv a7a8q e7e6 d6d5 e6h6 a8b8 h6e6 d5d4 e6e2
info depth 7 seldepth 9 multipv 1 score cp 190 nodes 326 nps 46571 tbhits 0 time 7 pv a7a8q e7e6 d6d5 e6h6 a8b8 h6e6 d5d4 e6e2 b8g3
info depth 8 seldepth 16 multipv 1 score cp 207 nodes 3601 nps 109121 tbhits 1 time 33 pv a7a8q e7e6 d6d5 e6h6 a8b8 h6e6 d5d4 e6c6 b8e5 c6e6 e5g5 d8c7 g5f5 b7b6
Could not mmap() /opt/picochess/tablebases/syzygy/KRBPvKQ.rtbw

using the same tablebases with 64 bit macOS , there is no error.

I believe it may have something to with the number of files being open?  Not sure.

Thanks in advanced.

**Comment by syzygy1** [comment]
Did you also modify these lines?
https://github.com/syzygy1/Cfish/blob/94172b34be585fa4b738a7ee3b0b6c4785b5fbe9/src/tbprobe.c#L416-L418

I would assume szeof(size_t) to be 4 on a 32-bit Linux OS, so 6-men TBs should not be loaded. A 32-bit address space is too small for 6-men TBs.

**Comment by syzygy1** [comment]
Ah, you're probably testing with Stockfish. So the answer is that a 32-bit address space is too small to map more than a few 6-men TBs into. To use 6-piece syzygy TBs, a 64-bit address space is required.

**Comment by MichaelB7** [comment]
Ok - so it sounds like there is no possible solution software solution ?

**Comment by syzygy1** [comment]
No solution short of rewriting the probing code to access the TB files with file operations such as fseek().

**Comment by MichaelB7** [comment]
Thanks for your responses.
