### ISSUE TITLE
Could not allocate sufficient memory.

### ISSUE THREAD

**Issue by sq5rix** [syzygy1/tb#30]
Hi
I have i7 with 16GB memory, clean 64-bit Ubuntu install
All 5 men tbs generate quickly 
I get the following:
rtbgen KQRvKRR -d
Found 145 tablebases.
number of threads = 1
Could not allocate sufficient memory.
Any chance?

**Comment by MichaelB7** [comment]
Read the readme.md.  You need to use the -d flag with 16GB.  If you had 24GB ram , -d flag is not needed.  Obviously using the -d flag will slow the generation down.   I created all 6 man using a 12 core Mac Pro with 32 GB ram.   Roughly 72 hours.

**Comment by sq5rix** [comment]
Thanks for the answer. 
I did use -d I went down to one thread too 
Can it be that swap is too small?

**Comment by sq5rix** [comment]
Ok, it was not enough memory, I rebooted and now it's running great!
