### ISSUE TITLE
memory issues

### ISSUE THREAD

**Issue by mattginsberg** [syzygy1/tb#34]
There are some array overruns in this code that are causing me fits.

1. In rtbgen.c rt and rtbgenp.c in the definition of calc_broken, idx is restricted to be less than end but that doesn't mean that idx+63 is less than end in the inner loop.

2. In the definitions of read_symbol and write_symbol in compress.c, the u8 case basically looks at *&x and *&(x + 1).  But if x is at the end of the array (and it sometimes is), this can cause trouble.

The first of these is easy to fix by adjusting the upper limit of the inner loop from 64 to min(64,end-idx).  The second is much more confusing.

**Comment by syzygy1** [comment]
Thanks for your interest :-)

In calc_broken() and calc_mates(), idx and end are always multiples of 64. So if idx < end, then idx + 63 < end.
https://github.com/syzygy1/tb/blob/9144c505823ff79bdaf48af89d3d8ff7e6d5720c/src/tbgen.c#L750

Certainly this could use a comment, but it is not the only comment missing.

The potential problem with read_symbol() and write_symbol() is taken care of by making sure the array is at least 1 byte too long. For example here:
https://github.com/syzygy1/tb/blob/9144c505823ff79bdaf48af89d3d8ff7e6d5720c/src/tbgen.c#L941

If I ever clean up the code (which is a mess, in particular the support for 7-piece tables and parallel generation of tables with many pawns), I might try to improve the documentation of the code as well.
