### ISSUE TITLE
Using context mixing instead of huffman encoding or LZP

### ISSUE THREAD

**Issue by absimaldata** [syzygy1/tb#35]
Syzygy tables are compressed using huffman encoding or lzp, if I am not wrong, I was thinking if we can use context mixing compression, like mcm, https://github.com/mathieuchartier/mcm

I think this is alot faster than even 7zip with more compression.

Benchmarks of mcm vs others, http://mattmahoney.net/dc/text.html
and we can see its too fast even at maximum settings from benchmarks, I have personally used it after compiling the source, so thats why suggesting the use of.

So what are your thoughts on this?

**Comment by syzygy1** [comment]
The TB data is compressed in blocks of 64 positions. General purpose compression algorithms are totally useless for that.
