### ISSUE TITLE
pawn generator rtbgenp

### ISSUE THREAD

**Issue by oppiet30** [syzygy1/tb#39]
How come it only generates up to d file and not up to h file?
Is it suppose to generate for half the board?

**Comment by syzygy1** [comment]
If the leading pawn is in the e file, you can mirror the position horizontally to get an equivalent position with that pawn on the d file. Same for f/c, g/b and h/a files. The probing code takes care of this. So the generator only needs to calculate positions with the leading pawn in the one of the a-d files.

If there are no pawns, then you can mirror the board horizontally, vertically and diagonally to force the white king (or the black king) to be in the a1-d1-d4 triangle. So the generator only calculates positions with the king on one of those squares (but you don't see that in the output).
