### ISSUE TITLE
Probably a probing error for the cloud interface

### ISSUE THREAD

**Issue by dcorbit** [syzygy1/tb#41]
If you enter this position:
2r1k2r/3R4/2p2K2/8/8/8/8/3R4 w k -
On the chess cloud interface to the 7 man Syzygy files, you get this response:
"This position is not analyzed yet, you can:"
and then there is a [Request for Analysis] button.
If you press the button, it says:
"Too few pieces on the board. You can:"
and then there is a button that says "AI Move"
If you press that button, nothing happens.
The cloud interface:
https://www.chessdb.cn/queryc_en/

It is also possible that there is a problem with the file.

**Comment by niklasf** [comment]
The position has remaining king-side castling rights, but Syzygy supports only endgame positions without castling rights.

**Comment by noobpwnftw** [comment]
This issue is fixed with https://github.com/noobpwnftw/chessdb/commit/0aa27920d500af5160a5a92fd0a11ad5507308e7.
