### ISSUE TITLE
Syzygy 8

### ISSUE THREAD

**Issue by ummite** [syzygy1/tb#44]
Is this code could be improved to generate Syzygy 8 ? I'm really interesting in helping for the coding part bug also provide high end computing capability and storage to achieve that.

**Comment by noobpwnftw** [comment]
You can start with generating 7 pieces tables to get yourself familiar with the code and the building process.

**Comment by ummite** [comment]
I've managed to create executable rtbgen on Windoes with cygwin/gcc/make and I've generate KQvK up to KQQvKQQ pretty easily.
When I try KQQvKQQQ, it show me
C:\Syzygy>rtbgen -d -s -t 32 KQQvKQQQ
Found 7 tablebases.
number of threads = 32
Initialising broken positions.
C:\Syzygy>

I suppose I get an out of memory or something, but since I've not managed to debug while running, I'm a little out of idea. I've tried both with -d and without -d.

My PC is Ryzen 7950 (16 cores) with 128GB ram and NVME as disks.

Is there something relatively simple for me to change in the code to allow running more complex scenarios?

Thanks!

**Comment by noobpwnftw** [comment]
Generally to build the full 7-piece set you'll need no less than 1TB of RAM, while for 8-piece tables it needs about 64TB of RAM, some extra indexing optimizations may get it down to about 40TB for particular tables like having two or more bishops of the same color, but that is not going to do much overall or for sub 8-pieces tables. Is this still relevant to you?
